server:
  port: 8443
  ssl:
    enabled: true
    key-alias: MyServer
    key-store-type: jks
    key-store: classpath:MyServer.jks
    key-store-password: password
    key-password: password
    trust-store: classpath:MyServer.jks
    trust-store-password: password  
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
auth:
  app:
    jwtSecret: jwtAuthSecretKey
    jwtExpiration: 86400  

  