server:
  port: 8085
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: tomcat
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
auth:
  app:
    jwtSecret: jwtAuthSecretKey
    jwtExpiration: 86400  
security:
  require-ssl: true
  