version: '3'
services:
    eureka:
        image: eureka-service
        container_name: eureka-service
        build:
            context: ./eureka-service
            dockerfile: Dockerfile
        ports:
          - "8761:8761"

    zuul:
        image: zuul-server
        container_name: zuul-server
        build:
            context: ./zuul-server
            dockerfile: Dockerfile
        ports:
          - "8081:8081"
        depends_on:
          - eureka
        links:
          - eureka:eureka

    agent:
        image: agent-service
        container_name: agent-service
        build:
            context: ./agent-service
            dockerfile: Dockerfile
        ports:
          - "8090"
        depends_on:
          - eureka
        links:
          - eureka:eureka

