version: '3'
services:
 
  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: megatravel
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
  
  accommodation-service:
    image: accommodation-service
    container_name: accommodation-service
    build:
        context: ./accommodation-service
        dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql