version: '3'
services:
    eureka:
        image: eureka-service
        container_name: eureka-service
        build:
            context: ./eureka-service
            dockerfile: Dockerfile
        ports:
          - "8761:8761"

    zuul:
        image: zuul-server
        container_name: zuul-server
        build:
            context: ./zuul-server
            dockerfile: Dockerfile
        ports:
          - "8081:8081"
        depends_on:
          - eureka
        links:
          - eureka:eureka

    agent:
        image: agent-service
        container_name: agent-service
        build:
            context: ./agent-service
            dockerfile: Dockerfile
        ports:
          - "8090"
        depends_on:
          - eureka
        links:
          - eureka:eureka


    accommodation:
            image: accommodation-service
            container_name: accommodation-service
            build:
                context: ./accommodation-service
                dockerfile: Dockerfile
            ports:
              - "8082"
            depends_on:
              - eureka
            links:
              - eureka:eureka


    reservation:
            image: reservation-service
            container_name: reservation-service
            build:
                context: ./reservation-service
                dockerfile: Dockerfile
            ports:
              - "8083"
            depends_on:
              - eureka
            links:
              - eureka:eureka


    auth:
            image: auth-service
            container_name: auth-service
            build:
                context: ./auth-service
                dockerfile: Dockerfile
            ports:
              - "8085"
            depends_on:
              - eureka
            links:
              - eureka:eureka

