// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package com.ftn.agentservice.chat;

public final class ChatOuterClass {
  private ChatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftn_agentservice_chat_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ftn_agentservice_chat_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nChat.proto\022\031com.ftn.agentservice.chat\"" +
      "%\n\007Message\022\014\n\004user\030\001 \001(\t\022\014\n\004text\030\002 \001(\t2\256" +
      "\001\n\004Chat\022T\n\004join\022\".com.ftn.agentservice.c" +
      "hat.Message\032\".com.ftn.agentservice.chat." +
      "Message\"\000(\0010\001\022P\n\004send\022\".com.ftn.agentser" +
      "vice.chat.Message\032\".com.ftn.agentservice" +
      ".chat.Message\"\000B\005P\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ftn_agentservice_chat_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ftn_agentservice_chat_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ftn_agentservice_chat_Message_descriptor,
        new java.lang.String[] { "User", "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
