// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package com.ftn.agentservice.chat;

/**
 * <pre>
 *Service class to be used by the clients
 * </pre>
 *
 * Protobuf service {@code com.ftn.agentservice.chat.Chat}
 */
public  abstract class Chat
    implements com.google.protobuf.Service {
  protected Chat() {}

  public interface Interface {
    /**
     * <code>rpc join(stream .com.ftn.agentservice.chat.Message) returns (stream .com.ftn.agentservice.chat.Message);</code>
     */
    public abstract void join(
        com.google.protobuf.RpcController controller,
        com.ftn.agentservice.chat.Message request,
        com.google.protobuf.RpcCallback<com.ftn.agentservice.chat.Message> done);

    /**
     * <code>rpc send(.com.ftn.agentservice.chat.Message) returns (.com.ftn.agentservice.chat.Message);</code>
     */
    public abstract void send(
        com.google.protobuf.RpcController controller,
        com.ftn.agentservice.chat.Message request,
        com.google.protobuf.RpcCallback<com.ftn.agentservice.chat.Message> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new Chat() {
      @java.lang.Override
      public  void join(
          com.google.protobuf.RpcController controller,
          com.ftn.agentservice.chat.Message request,
          com.google.protobuf.RpcCallback<com.ftn.agentservice.chat.Message> done) {
        impl.join(controller, request, done);
      }

      @java.lang.Override
      public  void send(
          com.google.protobuf.RpcController controller,
          com.ftn.agentservice.chat.Message request,
          com.google.protobuf.RpcCallback<com.ftn.agentservice.chat.Message> done) {
        impl.send(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.join(controller, (com.ftn.agentservice.chat.Message)request);
          case 1:
            return impl.send(controller, (com.ftn.agentservice.chat.Message)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.ftn.agentservice.chat.Message.getDefaultInstance();
          case 1:
            return com.ftn.agentservice.chat.Message.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.ftn.agentservice.chat.Message.getDefaultInstance();
          case 1:
            return com.ftn.agentservice.chat.Message.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc join(stream .com.ftn.agentservice.chat.Message) returns (stream .com.ftn.agentservice.chat.Message);</code>
   */
  public abstract void join(
      com.google.protobuf.RpcController controller,
      com.ftn.agentservice.chat.Message request,
      com.google.protobuf.RpcCallback<com.ftn.agentservice.chat.Message> done);

  /**
   * <code>rpc send(.com.ftn.agentservice.chat.Message) returns (.com.ftn.agentservice.chat.Message);</code>
   */
  public abstract void send(
      com.google.protobuf.RpcController controller,
      com.ftn.agentservice.chat.Message request,
      com.google.protobuf.RpcCallback<com.ftn.agentservice.chat.Message> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.ftn.agentservice.chat.ChatOuterClass.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.join(controller, (com.ftn.agentservice.chat.Message)request,
          com.google.protobuf.RpcUtil.<com.ftn.agentservice.chat.Message>specializeCallback(
            done));
        return;
      case 1:
        this.send(controller, (com.ftn.agentservice.chat.Message)request,
          com.google.protobuf.RpcUtil.<com.ftn.agentservice.chat.Message>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.ftn.agentservice.chat.Message.getDefaultInstance();
      case 1:
        return com.ftn.agentservice.chat.Message.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.ftn.agentservice.chat.Message.getDefaultInstance();
      case 1:
        return com.ftn.agentservice.chat.Message.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.ftn.agentservice.chat.Chat implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void join(
        com.google.protobuf.RpcController controller,
        com.ftn.agentservice.chat.Message request,
        com.google.protobuf.RpcCallback<com.ftn.agentservice.chat.Message> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.ftn.agentservice.chat.Message.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.ftn.agentservice.chat.Message.class,
          com.ftn.agentservice.chat.Message.getDefaultInstance()));
    }

    public  void send(
        com.google.protobuf.RpcController controller,
        com.ftn.agentservice.chat.Message request,
        com.google.protobuf.RpcCallback<com.ftn.agentservice.chat.Message> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.ftn.agentservice.chat.Message.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.ftn.agentservice.chat.Message.class,
          com.ftn.agentservice.chat.Message.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.ftn.agentservice.chat.Message join(
        com.google.protobuf.RpcController controller,
        com.ftn.agentservice.chat.Message request)
        throws com.google.protobuf.ServiceException;

    public com.ftn.agentservice.chat.Message send(
        com.google.protobuf.RpcController controller,
        com.ftn.agentservice.chat.Message request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.ftn.agentservice.chat.Message join(
        com.google.protobuf.RpcController controller,
        com.ftn.agentservice.chat.Message request)
        throws com.google.protobuf.ServiceException {
      return (com.ftn.agentservice.chat.Message) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.ftn.agentservice.chat.Message.getDefaultInstance());
    }


    public com.ftn.agentservice.chat.Message send(
        com.google.protobuf.RpcController controller,
        com.ftn.agentservice.chat.Message request)
        throws com.google.protobuf.ServiceException {
      return (com.ftn.agentservice.chat.Message) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.ftn.agentservice.chat.Message.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:com.ftn.agentservice.chat.Chat)
}

