// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package com.ftn.agentservice.chat;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ftn.agentservice.chat.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string text = 2;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
