server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:zuul.jks
    key-store-password: ${KEY_STORE_PASSWORD}
    trust-store: classpath:trust-zuul.jks
    trust-store-password: ${KEY_STORE_PASSWORD}
    key-alias: zuul
security:
  require-ssl: true
spring:
  application:
    name: zuul-server
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 8081
    statusPageUrl: https://localhost:8081/info
    healthCheckUrl: https://localhost:8081/health
    homePageUrl: https://localhost:8081
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka
zuul:
  routes:
    reservationservice:
      serviceId: reservation-service
    accommodationservice:
      serviceId: accommodation-service
    bezbednost:
      serviceId: pki-service
  host:
    socket-timeout-millis: 30000
ribbon:
  IsSecure: true
