    
server:
  port: 8081
spring:
  application:
    name: zuul-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  routes:
    reservationservice:
      serviceId: reservationservice
  host:
    socket-timeout-millis: 30000
logging:
  level:
    ROOT: INFO
    org.springframework: ERROR
    com.fd: TRACE
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss} - %msg%n"