server:
  port: 8081
  ssl:
    enabled: false
    key-store: classpath:zuul.jks
    key-store-password: ${KEY_STORE_PASSWORD}
    trust-store: classpath:trust-zuul.jks
    trust-store-password: ${KEY_STORE_PASSWORD}
    key-alias: zuul
security:
  require-ssl: false
spring:
  application:
    name: zuul-server
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: false
    securePort: 8081
    statusPageUrl: http://localhost:8081/info
    healthCheckUrl: http://localhost:8081/health
    homePageUrl: http://localhost:8081
  client:
    securePortEnabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    reservationservice:
      serviceId: reservation-service
    accommodationservice:
      serviceId: accommodation-service
    bezbednost:
      serviceId: pki-service
  host:
    socket-timeout-millis: 30000
ribbon:
  IsSecure: false
