spring:
  application:
    name: zuul-server
server:  
  port: ${PORT:8081}
  ssl:
    enabled: true
    key-store: classpath:zuul.jks
    key-store-password: password
    key-alias: zuul
    
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ 
zuul:
  routes:
    reservationservice:
      serviceId: reservation-service
    accommodationservice:
      serviceId: accommodation-service
    bezbednost:
      serviceId: pki-service
    agentservice:
      serviceId: agent-service
    authservice:
       serviceId: auth-service
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 30000
  sslHostnameValidationEnabled: false
ribbon:
  IsSecured: true
  ConnectTimeout:  10000
  ReadTimeout:  10000
  eureka:
    enabled: true
  TrustStore: classpath:zuul.jks
  TrustStorePassword : password
  IsHostnameValidationRequired: false