spring:
  application:
    name: zuul-server
server:  
  port: ${PORT:8081}
  ssl:
    enabled: true
    key-store: classpath:zuul.jks
    key-store-password: password
    key-alias: zuul
    
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    preferIpAddress: false
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    securePortEnabled: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ 
zuul:
  routes:
    reservationservice:
      serviceId: reservation-service
    accommodationservice:
      serviceId: accommodation-service
    bezbednost:
      serviceId: pki-service
  host:
    socket-timeout-millis: 30000
  sslHostnameValidationEnabled: false
ribbon:
  IsSecured: true
  eureka:
    enabled: true
  TrustStore: classpath:zuul.jks
  TrustStorePassword : password
  IsHostnameValidationRequired: false