server:
  port: 8081
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    customer-service:
      serviceId: customer-service
  host:
    socket-timeout-millis: 30000 