server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:accommodationkeystore.jks
    key-store-password: password
    trust-store: classpath:accommodationtruststore.jks
    trust-store-password: password
    key-alias: acc
security:
  require-ssl: true 
spring:
  application:
    name: accommodation-service
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
debug: true