server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:MyClient.jks
    key-store-password: password
    key-alias: MyClient
security:
  require-ssl: true 
spring:
  application:
    name: accommodation-service
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    securePortEnabled: true
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/