server:  
  port: ${PORT:8082}
  ssl:
    enabled: true
    key-store: ${KEY_STORE_CLASSPATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_ALIAS}
web:
  service:
    username: ${WEB_SERVICE_USERNAME}
    password: ${WEB_SERVICE_PASSWORD}
    
security:
  require-ssl: true
  
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: ${CLIENT_SERVICEURL_DEFAULTZONE}
spring:
  application:
    name: accommodation-service
  datasource:
    url: jdbc:mysql:${DATASOURCE_URL_JDBC_MYSQL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
