server:
  port: 8082
  ssl:
    enabled: false
    key-store: classpath:MyClient.jks
    key-store-password: password
    key-alias: MyClient
security:
  require-ssl: false 
spring:
  application:
    name: accommodation-service
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: false
    securePort: ${server.port}
    statusPageUrl: http://localhost:${server.port}/info
    healthCheckUrl: http://localhost:${server.port}/health
    homePageUrl: http://localhost:${server.port}
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/