server:
  port: 8082
  ssl:
    enabled: false
    key-store: classpath:accommodation-service.jks
    key-store-password: password
    key-alias: accommodation-service
security:
  require-ssl: false 
spring:
  application:
    name: accommodation-service
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
debug: true