server:
  port: 8083
  ssl:
    enabled: true
    key-store: classpath:Reservation.jks
    key-store-password: password
    key-alias: reservation
security:
  require-ssl: true   
spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  level:
    ROOT: INFO
    org.springframework: ERROR
    com.fd: TRACE
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss} - %msg%n"