server:  
  port: ${PORT:8091}
  ssl:
    enabled: true
    key-store: classpath:agent.jks
    key-store-password: password
    key-alias: agent
web:
  service:
    username: nemanjica
    password: password
        
security:
  require-ssl: true
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ 
spring:
  application:
    name: agent-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
        enabled: true
        path: /h2console/