server:  
  port: ${PORT:8085}
  ssl:
    enabled: true
    key-store: ${KEY_STORE_CLASSPATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_ALIAS}
    
security:
  require-ssl: true
  
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: ${CLIENT_SERVICEURL_DEFAULTZONE}
spring:
  application:
    name: auth-service
  datasource:
    url:  ${DATASOURCE_URL_JDBC_MYSQL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    debug: true
    port: 465
    transport:
      protocol: smtp
    smtp:
      auth: true
      starttls:
        enable : true
        require: true
      ssl: true

auth:
  app:
    jwtSecret: ${AUTH_APP_JWTSECRET}
    jwtExpiration: 864000
