server:  
  port: ${PORT:8085}
  ssl:
    enabled: true
    key-store: classpath:auth.jks
    key-store-password: password
    key-alias: auth
    
security:
  require-ssl: true
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ 
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: af083085@gmail.com
    password: ovojetest123
    debug: true
    port: 465
    transport:
      protocol: smtp
    smtp:
      auth: true
      starttls:
        enable : true
        require: true
      ssl: true

auth:
  app:
    jwtSecret: jwtAuthSecretKey
    jwtExpiration: 864000
