server:
  port: 8761
  ssl:
    enabled: false
    key-store: classpath:eureka.jks
    key-store-password: ${KEY_STORE_PASSWORD}
    trust-store: classpath:eureka.jks
    trust-store-password: ${KEY_STORE_PASSWORD}
    key-alias: eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true
    securePortEnabled: false
    nonSecurePortEnabled: false