spring:
  application:
    name: eureka-service

server:
  port: 8761
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:eureka.jks
    key-store-password: password
    key-alias: eureka
    trust-store: classpath:eureka.jks
    trust-store-password: password
    
eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    preferIpAddress: true
    nonSecurePortEnabled: false 
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
  client:
    registerWithEureka: false
    fetchRegistry: false