server:
  port: 8761
  ssl:
    enabled: false
    key-store: classpath:eureka-service.jks
    key-store-password: password
    trust-store: classpath:eureka-service.jks
    trust-store-password: password
    key-alias: eureka-service
debug: true
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF