spring:
  application:
    name: eureka-service

server:
  port: 8761
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:eureka.jks
    key-store-password: password
    key-alias: eureka
    trust-store: classpath:eureka.jks
    trust-store-password: password
    
eureka:
  instance:
    securePort: ${server.port}
    securePortEnabled: true
    prefer-ip-address: true
    nonSecurePortEnabled: false 
  client:
    registerWithEureka: false
    fetchRegistry: false