server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:MyServer.jks
    key-store-password: password
    trust-store: classpath:MyServer.jks
    trust-store-password: password
    key-alias: MyServer
    client-auth: need
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF