//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 10:58:37 PM CEST 
//


package com.ftn.accommodationservice.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.accommodationservice.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.accommodationservice.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link PostAccommodationObjectResponse }
     * 
     */
    public PostAccommodationObjectResponse createPostAccommodationObjectResponse() {
        return new PostAccommodationObjectResponse();
    }

    /**
     * Create an instance of {@link PostReservationBusynessResponse }
     * 
     */
    public PostReservationBusynessResponse createPostReservationBusynessResponse() {
        return new PostReservationBusynessResponse();
    }

    /**
     * Create an instance of {@link GetAddressResponse }
     * 
     */
    public GetAddressResponse createGetAddressResponse() {
        return new GetAddressResponse();
    }

    /**
     * Create an instance of {@link GetTestResponse }
     * 
     */
    public GetTestResponse createGetTestResponse() {
        return new GetTestResponse();
    }

    /**
     * Create an instance of {@link PostAccommodationObjectRequest }
     * 
     */
    public PostAccommodationObjectRequest createPostAccommodationObjectRequest() {
        return new PostAccommodationObjectRequest();
    }

    /**
     * Create an instance of {@link GetTypeResponse }
     * 
     */
    public GetTypeResponse createGetTypeResponse() {
        return new GetTypeResponse();
    }

    /**
     * Create an instance of {@link PostReservationCompletionRequest }
     * 
     */
    public PostReservationCompletionRequest createPostReservationCompletionRequest() {
        return new PostReservationCompletionRequest();
    }

    /**
     * Create an instance of {@link GetAdditionalServiceResponse }
     * 
     */
    public GetAdditionalServiceResponse createGetAdditionalServiceResponse() {
        return new GetAdditionalServiceResponse();
    }

    /**
     * Create an instance of {@link GetCategoryResponse }
     * 
     */
    public GetCategoryResponse createGetCategoryResponse() {
        return new GetCategoryResponse();
    }

    /**
     * Create an instance of {@link GetCategoryRequest }
     * 
     */
    public GetCategoryRequest createGetCategoryRequest() {
        return new GetCategoryRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link PostReservationCompletionResponse }
     * 
     */
    public PostReservationCompletionResponse createPostReservationCompletionResponse() {
        return new PostReservationCompletionResponse();
    }

    /**
     * Create an instance of {@link PostAddressResponse }
     * 
     */
    public PostAddressResponse createPostAddressResponse() {
        return new PostAddressResponse();
    }

    /**
     * Create an instance of {@link GetAccUnitPriceRequest }
     * 
     */
    public GetAccUnitPriceRequest createGetAccUnitPriceRequest() {
        return new GetAccUnitPriceRequest();
    }

    /**
     * Create an instance of {@link PostAddressRequest }
     * 
     */
    public PostAddressRequest createPostAddressRequest() {
        return new PostAddressRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationObjectRequest }
     * 
     */
    public GetAccommodationObjectRequest createGetAccommodationObjectRequest() {
        return new GetAccommodationObjectRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitRequest }
     * 
     */
    public GetAccommodationUnitRequest createGetAccommodationUnitRequest() {
        return new GetAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link AccUnitPrice }
     * 
     */
    public AccUnitPrice createAccUnitPrice() {
        return new AccUnitPrice();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link GetAddressRequest }
     * 
     */
    public GetAddressRequest createGetAddressRequest() {
        return new GetAddressRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationObjectResponse }
     * 
     */
    public GetAccommodationObjectResponse createGetAccommodationObjectResponse() {
        return new GetAccommodationObjectResponse();
    }

    /**
     * Create an instance of {@link GetTypeRequest }
     * 
     */
    public GetTypeRequest createGetTypeRequest() {
        return new GetTypeRequest();
    }

    /**
     * Create an instance of {@link GetAllAdditionalServiceResponse }
     * 
     */
    public GetAllAdditionalServiceResponse createGetAllAdditionalServiceResponse() {
        return new GetAllAdditionalServiceResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitResponse }
     * 
     */
    public GetAccommodationUnitResponse createGetAccommodationUnitResponse() {
        return new GetAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link GetTestRequest }
     * 
     */
    public GetTestRequest createGetTestRequest() {
        return new GetTestRequest();
    }

    /**
     * Create an instance of {@link GetAccUnitPriceResponse }
     * 
     */
    public GetAccUnitPriceResponse createGetAccUnitPriceResponse() {
        return new GetAccUnitPriceResponse();
    }

    /**
     * Create an instance of {@link AdditionalService }
     * 
     */
    public AdditionalService createAdditionalService() {
        return new AdditionalService();
    }

    /**
     * Create an instance of {@link AccommodationObject }
     * 
     */
    public AccommodationObject createAccommodationObject() {
        return new AccommodationObject();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link GetAllAdditionalServiceRequest }
     * 
     */
    public GetAllAdditionalServiceRequest createGetAllAdditionalServiceRequest() {
        return new GetAllAdditionalServiceRequest();
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link GetAdditionalServiceRequest }
     * 
     */
    public GetAdditionalServiceRequest createGetAdditionalServiceRequest() {
        return new GetAdditionalServiceRequest();
    }

    /**
     * Create an instance of {@link PostReservationBusynessRequest }
     * 
     */
    public PostReservationBusynessRequest createPostReservationBusynessRequest() {
        return new PostReservationBusynessRequest();
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

}
